module.exports.assets = require "./plugins/assets"
module.exports.bower = require "./plugins/bower"
module.exports.crud = require "./plugins/crud"
module.exports.express = require "./plugins/express"
module.exports.files = require "./plugins/files"
module.exports.fixtures = require "./plugins/fixtures"
module.exports.mongoose = require "./plugins/mongoose"
